########################################################################
# Project : TouLaMeche
# File    : Makefile
# =============================================================
# Description : General-purpose build system for the project.
#               Handles automatic dependency tracking, incremental
#               compilation, linking against pre-built object files,
#               and standard clean targets.
# =============================================================
# Author  : Nachid Ayman
########################################################################

# ---------------------------------------------------------------------
# Toolchain
# ---------------------------------------------------------------------

# C compiler to use for all compilation and linking steps
CC := gcc

# Compilation flags:
#   -Wall -Wextra -Werror : enable and promote all warnings to errors
#   -std=c11              : enforce the C11 standard
#   -g                    : embed debug symbols (for gdb / valgrind)
CFLAGS := -Wall -Wextra -Werror -std=c11 -g

# ---------------------------------------------------------------------
# Target and sources
# ---------------------------------------------------------------------

# Name of the final executable produced by the linker
TARGET := main

# Collect all .c files in the current directory, excluding standalone
# test/example files that define their own main() and must not be
# linked into the main binary
SRC := $(filter-out test_hash.c, $(wildcard *.c))

# Derive object file names from source file names (.c -> .o)
OBJ := $(SRC:.c=.o)

# Pre-built external object files (architecture-specific, do not remove)
# These provide the hash table and linked-list implementations
EXT_OBJ := hash_x86_64.o list_x86_64.o

# Automatic dependency files generated by -MMD/-MP (one per object file)
# They track #include relationships so that editing a header triggers
# the recompilation of every affected translation unit
DEP := $(OBJ:.o=.d)

########################################################################
# Primary targets
########################################################################

# Default target: build the executable
all: $(TARGET)

# Link all object files (project + external) into the final binary.
# -lm is appended last so the linker resolves math library symbols
# (e.g. sqrt) that may be referenced by earlier object files.
$(TARGET): $(OBJ) $(EXT_OBJ)
	$(CC) $(CFLAGS) -o $@ $^ -lm

########################################################################
# Compilation rule
########################################################################

# Pattern rule: compile any .c file into the corresponding .o file.
#   -MMD : generate a .d dependency file as a side effect
#   -MP  : add phony targets for headers to avoid errors on deletion
%.o: %.c
	$(CC) $(CFLAGS) -MMD -MP -c $< -o $@

########################################################################
# Execution
########################################################################

# Build (if necessary) and run the executable in the current directory
run: $(TARGET)
	./$(TARGET)

########################################################################
# Clean targets
########################################################################

# Remove compiled object files and dependency files, keep the binary
clean:
	rm -f $(OBJ) $(DEP)

# Full clean: remove everything produced by the build (binary included)
fclean: clean
	rm -f $(TARGET)

# Rebuild from scratch: full clean followed by a complete build
re: fclean all

########################################################################
# Automatic dependency inclusion
########################################################################

# Include all generated .d files if they exist.
# The leading '-' suppresses errors on first build when no .d files
# have been generated yet.
-include $(DEP)

# Declare phony targets so Make never confuses them with file names
.PHONY: all run clean fclean re